### ISSUE TITLE
feat(next version): report as inspections, not tests

### ISSUE THREAD

**Issue by akaguny** [andreogle/eslint-teamcity#10]
https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-Inspectiontype
we may report eslint violations as inspection errors, not tests
If we are use that we must push any new error type as ispection type: example:
##teamcity[inspectionType id='indent' name='<name>' description='<description>' category='eslint']
and then error:
##teamcity[inspection typeId='<inspection type identity>' message='line 10, col 1, Expected indentation of 0 spaces but found 1. (indent)' file='/temp/anyPath/file.js' line='1' additional attribute='ERROR']

**Comment by andreogle** [comment]
I think that this makes sense. Thanks for finding the docs.

Will try to get around to it sometime this week (hopefully)

**Comment by akaguny** [comment]
@andreogle maybe you create project eslint-teamcity 2.0, where we can put any features for 2.0?)

**Comment by andreogle** [comment]
I think I'll just create a branch rather and we can just use that to test. It's just more work to create a new project and might be confusing to someone looking at the package for the first time.

You can specify a branches for `package.json` dependencies, so we can just use that when testing.

**Comment by akaguny** [comment]
@andreogle create project in github it's very simple, i'm create this for organize my own issues in my project https://github.com/akaguny/advanced-build-conditions/projects

**Comment by andreogle** [comment]
Oh thought you meant a separate repo, sorry. Haven't used projects before.

I've created a new project and added this issue to the board: https://github.com/andreogle/eslint-teamcity/projects/1#card-4934146

**Comment by akaguny** [comment]
you may put on the desc issue from issue directly

**Comment by andreogle** [comment]
Created a new issue directly from the projects board, so going to close this one
