### ISSUE TITLE
Getting an inspection without and id causing TeamCity to error.

### ISSUE THREAD

**Issue by liazy** [andreogle/eslint-teamcity#75]
The package is generating the output: 
>##teamcity[inspectionType **id=''** category='ESLint Violations' name='' description='ESLint Violations']
>##teamcity[inspection **typeId=''** message='line 84, col 18, Parsing error: Unexpected token i' file='MyFile.js' line='84' SEVERITY='ERROR']

Which is causing teamcity to show the error: 
>[21:27:46][Step 5/17] Attributes id, name, category, description are required to 'inspectionType' service message
>[21:27:46][Step 5/17] Attributes 'typeId' and 'file' are required to 'inspection' service message

The offending code is:
>for (**let i** = 0, length = this.formControlOptions.length; i < length; i++) { }

This code is invalid because our config is set to ES5:
>{
>	"parserOptions": { "ecmaVersion": 5 },
>    "rules": {
>		"arrow-body-style": ["error", "never"]
>    }
>} 

Would it be possible to add a default Id to avoid this issue please?

P.S. Thanks for creating this package!

**Comment by andreogle** [comment]
Hey! Sorry for the slow response.

I'm not quite sure that I understand how this is happening. What version of Node are you running? 

The `id` and `typeId` fields are coming directly from the `ruleId` fields that ESLint itself provides (https://eslint.org/docs/developer-guide/working-with-custom-formatters#the-message-object). These must be empty string/null/undefined in this case which leads me to think that this may be an ESLint bug? I've never seen messages come through without a `ruleId` before.

I don't mind adding a default, although I'd first like to understand what's causing `ruleId` to be blank if possible. 

Are you able to provide a minimal reproduction repo that I could use to test with?

**Comment by liazy** [comment]
Hi,

ESLint is not returning a ruleId in this instance because it is a parser error rather than an unmet rule.

I have created an simple example here: https://github.com/liazy/eslint-noidexample. You can see from this example that ESLint is not outputting a ruleId.

**Comment by andreogle** [comment]
Thanks for the example repo. Yeah I see that you're right. It makes sense. If ESLint can't parse the syntax in the file, then obviously it can't apply a ruleId.

I also checked the types for ESLint and you can see that `ruleId` can be `string` or `null`. https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/eslint/index.d.ts#L464

Do you have any preferences for a default value? How about `<none>`?

**Comment by liazy** [comment]
I don't mind as long as teamcity is happy with it. I guess `<none>` or `<unknown>` is better than `parser-error` as they are less likely to clash with rule ids and I imagine there may be other things that could output without an rule id.

**Comment by andreogle** [comment]
Ok cool. I'll try it out locally just to see that TeamCity is happy and hopefully get a new version out tomorrow

**Comment by andreogle** [comment]
A default of `<none>` has been added in version 3.0.1. I tested locally and it seems to work fine, but let me know if you have any issues with it

**Comment by liazy** [comment]
That's sorted the issue for me. Thanks for for your help.
