### ISSUE TITLE
Fails on system

### ISSUE THREAD

**Issue by jessepinuelas** [andreogle/eslint-teamcity#8]
I have been running into this issue on a project that I am working on. When I run this from a scripts in my package.json
`"lint-js-teamcity": "eslint . -f node_modules/eslint-html-reporter/reporter-team-city.js -o ESLintReport.html"`

It lints everything and produces the html file but it fails right after. Not sure exactly why.
**node version:** 6.11.0
**npm version:** 3.10.10

**npm ERR! Tell the author that this fails on your system:**
npm ERR! eslint . -f node_modules/eslint-html-reporter/reporter-team-city.js -o ESLintReport.html

**Comment by andreogle** [comment]
Hey!

Seems like you're using a different package, specifically this one: https://www.npmjs.com/package/eslint-html-reporter. You might want to log the issue with them rather 😉 

Otherwise, you could replace:
```
eslint . -f node_modules/eslint-html-reporter/reporter-team-city.js -o ESLintReport.html"
```
with:
```
eslint . -f node_modules/eslint-teamcity/index.js
```
but this won't give you an HTML file in the output.

**Comment by jessepinuelas** [comment]
@andreogle thanks not sure how I missed that LOL. Thanks for the quick response.

Cheers

**Comment by jessepinuelas** [comment]
@andreogle I installed eslint-teamcity package, ran npm cache clean and replaced my npm script and I get the following error

`Failed at the pri@0.0.1 lint-js-teamcity script 'eslint . -f node_modules/eslint-teamcity/index.js'`

**In debug log:**
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\username\AppData\Roaming\nvm\v6.11.0\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\username\AppData\Roaming\nvm\v6.11.0\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

Is there a dep that I am missing?

**Comment by andreogle** [comment]
Hmmm. Nothing obvious from the log. How are you running your script? Does your package.json look like this?
```
...
"scripts": {
  "lint-js-teamcity": "eslint . -f node_modules/eslint-teamcity/index.js'"
}
...
```
And you're running it with `npm run lint-js-teamcity`?

I assume that you have ESLint installed globally? What about if you add it to your package.json and modify your script to be:

```
"lint-js-teamcity": "node node_modules/.bin/eslint . -f node_modules/eslint-teamcity/index.js'"
```

**Comment by andreogle** [comment]
Does it work if you run ESLint without the formatter?

**Comment by jessepinuelas** [comment]
If I remove the formatter or pass it stylish it does not throw the error, but prompts to use the following: File ignored by default. Use "--ignore-pattern '!node_modules/*'" to override

**Comment by jessepinuelas** [comment]
Yes eslint is installed globally and below is how I am running the script

**If I run**
`"scripts": {
"lint-js-teamcity": "eslint . node_modules/eslint-teamcity/index.js"
}
`
The linting runs fine but after fails with the original error I posted eslint . node_modules/eslint-teamcity/index.js


**If I run**
`"scripts": {
"lint-js-teamcity": "eslint node_modules/eslint-teamcity/index.js"
}
`
No linting is ran and I get this message
0:0  warning  File ignored by default. Use "--ignore-pattern '!node_modules/*'" to override

**Comment by andreogle** [comment]
Your first example is missing the `-f` flag (not sure if this was a mistake or not).

Your second example will attempt to lint the teamcity-eslint index.js file (instead of your project folder), but will get ignored because the entire node_modules folder is ignored by default.

If you try run just `eslint .`, does that work?

**Comment by jessepinuelas** [comment]
**Running**
`eslint .`

**Will run and lint all files but after fails with:**
Failed at pri@0.0.1 lint-js-teamcity script 'eslint .'

**Comment by andreogle** [comment]
I don't understand. It successfully runs and lints everything and then fails afterwards? If `eslint .` is throwing weird errors, it's definitely not a problem with teamcity-eslint.

What about if you run `node node_modules/.bin/eslint .`? Same thing? Have you got valid `.eslintrc` and `.eslintignore` files if you're using those?

This may also be an issue with node/eslint on windows. I'm not sure. I don't have enough experience with node on windows to be able to debug if it is a problem with that

**Comment by jessepinuelas** [comment]
Same thing, no worries @andreogle I guess I will continue trouble shooting and if I find a solution I will let you know. Thanks for your time, much appreciated.

**Comment by andreogle** [comment]
Cool. Sorry that I wasn't able to help any more than that. Good luck!

**Comment by jessepinuelas** [comment]
@andreogle Just wanted to give you an update. The error 14 verbose stack Exit status 1 was because there were errors and eslint will set the status to 1 if there are any errors. The problem I was facing was that there were legacy files in our system that contained errors so in team city I had to display the linting output but silent the npm error.

`npm {name-of-script} -s`

 Did the trick

**Comment by andreogle** [comment]
Awesome! That's great to know. Thanks for the update 👍
