### ISSUE TITLE
feat/bugfix(*): don`t group errors in file

### ISSUE THREAD

**Issue by akaguny** [andreogle/eslint-teamcity#9]
current version group errors in one file to 1 test, and display errors as staktrace of the test.
but it is'nt truthly - if we have different errors in one file we dosn't have new error, because this file(test) was failed in previous build of the branch.

**Comment by andreogle** [comment]
I'm not sure that I understand. Would you be able to give some an example of what the current output is and what the expected output should be?

**Comment by akaguny** [comment]
yes, example:
i have errors in fileOne.js, in teamcity is
error:
fileOne.js:
stacktrace:
error at line1
error at line2
error at line3
error fileOne.js it's new error, teamcity mark it as new error, allright, but in the next build i fixed error at lint 1 and create new error at line 67, in teamcity:
error:
fileOne.js:
stacktrace:
error at line2
error at line3
error at line67
i see that error at line 67 new, but teamcity dosn`t now about it because error is fileOne.js and its old.

**Comment by andreogle** [comment]
Ah I see what you're saying. I'm not sure that there is a way to handle this since I think TeamCity marks items as "new" and not something that eslint-teamcity does. I'll take a look in their docs but can't promise anything.

**Comment by andreogle** [comment]
I think it also makes sense that TeamCity handles this because eslint-teamcity has no knowledge of what is new and what isn't. We have no way of knowing what was run in the previous build (only TeamCity knows this). eslint-teamcity simply gets a list of errors as output from ESLint and formats accordingly.

**Comment by akaguny** [comment]
i know how eslint-teamcity works)
i talk about outputs of errors. Now many arrors display at 1 erorr - stacktrace, maybe as independent errors?

**Comment by andreogle** [comment]
ok I think I get it. However, I'm not really a fan of having individual errors instead of errors grouped by file. 

Maybe, it would be better if we could have an additional flag or some configuration (in package.json?) that could either group errors by filename (the default) or have independent errors if the option is specified?

**Comment by akaguny** [comment]
why? when you counting errors and warning you are counting errors as individual, not groupped. But when you show errors to user they grouped?)

**Comment by andreogle** [comment]
Sorry for the slow replies - been really busy at work.

Yes I think not grouping the total error count makes sense. I can't see how it would work if you had an error count for each file and then tried to generate a build statistics graph (the only place that total error/warning counts are be used). You would potentially have 100s of lines on the graph. The total count is only to get an idea of whether or not you are increasing or decreasing overall errors over time.

I also still think having errors grouped per file makes more sense. If you had no grouping and a large number of errors, you would just get a wall of red text - which is difficult to read and even harder to make use of. You would also need to include the filename as well somewhere in each error. The grouping of errors per file is more intuitive and much cleaner.

However, I can see that this has value to at least 1 person so I'm open to having a non-intrusive configuration setting that could output errors that are not grouped.

**Comment by akaguny** [comment]
may be need see into the classes of tests Teamcity
teamcity hav hierarhy near that:
suites > classes > tests
maybe make classes === files?

**Comment by andreogle** [comment]
That could potentially work. I don't know enough about this to really say. Have you got a link to the docs about this?

**Comment by akaguny** [comment]
https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-ReportingTests
Teamcity parse test name by dot https://confluence.jetbrains.com/display/TCD10/Build+Script+Interaction+with+TeamCity#BuildScriptInteractionwithTeamCity-Interpretingtestnames

**Comment by andreogle** [comment]
cool, thanks. I'll have a look soon
